aidl: Fix mismatched types
* bwa
  --> hardware/transsion/aidl/light/lights.rs:65:17
   |
65 |             id: LightType::BACKLIGHT as i32,
   |                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^ an `as` expression can only be used to convert between primitive types or to coerce to a specific trait object

error[E0308]: mismatched types
  --> hardware/transsion/aidl/light/lights.rs:94:94
   |
94 |                     return Err(Status::new_exception(ExceptionCode::TRANSACTION_FAILED, Some(&msg)));
   |                                                                                         ---- ^^^^ expected `&CStr`, found `&String`
   |                                                                                         |
   |                                                                                         arguments to this enum variant are incorrect
   |
   = note: expected reference `&std::ffi::CStr`
              found reference `&std::string::String`
help: the type constructed contains `&std::string::String` due to the type of the argument passed
  --> hardware/transsion/aidl/light/lights.rs:94:89
   |
94 |                     return Err(Status::new_exception(ExceptionCode::TRANSACTION_FAILED, Some(&msg)));
   |                                                                                         ^^^^^----^
   |                                                                                              |
   |                                                                                              this argument influences the type of `Some`
note: tuple variant defined here
  --> ./prebuilts/rust/linux-x86/1.83.0/lib/rustlib/src/rust/library/core/src/option.rs:579:5

Signed-off-by: Shirayuki39 <lorddemecrius83@proton.me>
Signed-off-by: fjrXTR <fajarslebew31@gmail.com>